# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 00:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bi', models.PositiveIntegerField(blank=True, null=True)),
                ('morada', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=8, null=True)),
                ('localidade', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone', models.PositiveIntegerField(blank=True, null=True)),
                ('nro_eleitor', models.PositiveIntegerField(blank=True, null=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=3000)),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('data_evento', models.DateField()),
                ('imagem', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ficheiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=3000)),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ACAO', 'Plano de Acao'), ('CONTAS', 'Relatorio de Contas'), ('ACTAS', 'Actas de Reuniao'), ('OUTRO', 'Outros')], default='OUTRO', max_length=20)),
                ('ficheiro', models.FileField(upload_to='documents/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('remetente', models.CharField(max_length=50)),
                ('assunto', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=50)),
                ('mensagem', models.CharField(max_length=500)),
                ('telefone', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=3000)),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=3000)),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=3000)),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('quest', models.CharField(max_length=400)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Pergunta')),
                ('respondido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Opcao')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='opcao',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Pergunta'),
        ),
    ]
