# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votacao',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='votacao',
            name='respondido',
        ),
        migrations.RemoveField(
            model_name='votacao',
            name='utilizador',
        ),
        migrations.DeleteModel(
            name='Votacao',
        ),
    ]
