# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170518_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(upload_to='events_images/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(upload_to='news_images/'),
        ),
    ]
