# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170528_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='events_images/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
