# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_auto_20170529_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('E1', 'Em Análise'), ('E2', 'Aguarda Pagamento'), ('E3', 'Rever Requerimento'), ('E4', 'A Processar Documento'), ('E5', 'Diferido'), ('E6', 'Recusado')], max_length=20)),
                ('data_req', models.DateTimeField(auto_now_add=True)),
                ('data_ult_atual', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='cidadao',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='mae',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='pai',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='ocorr_images/'),
        ),
        migrations.AddField(
            model_name='requerimento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Servico'),
        ),
        migrations.AddField(
            model_name='requerimento',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
