# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20170531_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
