# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_servico_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimento',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='user_documents/'),
        ),
        migrations.AddField(
            model_name='requerimento',
            name='envio',
            field=models.CharField(blank=True, choices=[('C', 'Correio'), ('L', 'Levantamento na Junta')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requerimento',
            name='pagamento',
            field=models.CharField(blank=True, choices=[('J', 'Pagar na Junta'), ('O', 'Pagar Online')], max_length=20, null=True),
        ),
    ]
