# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20170601_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimento',
            name='envio',
            field=models.CharField(blank=True, choices=[('C', 'Correio'), ('L', 'Levantamento na Junta')], default='C', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requerimento',
            name='pagamento',
            field=models.CharField(blank=True, choices=[('J', 'Pagar na Junta'), ('O', 'Pagar Online')], default='O', max_length=20, null=True),
        ),
    ]
