# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20170601_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimento',
            name='mensagem',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='requerimento',
            name='estado',
            field=models.CharField(choices=[('E1', 'Em Análise'), ('E2', 'Aguarda Pagamento'), ('E3', 'Diferido'), ('E4', 'Recusado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
