# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20170602_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimento',
            name='descricao',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='requerimento',
            name='estado',
            field=models.CharField(choices=[('ANALISE', 'Em Análise'), ('PAGAMENTO', 'Aguarda Pagamento'), ('DIFERIDO', 'Diferido'), ('RECUSADO', 'Recusado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='requerimento',
            name='mensagem',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
