# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20170607_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='num_bi',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
